import * as React from "react";
import { useTranslation } from "react-i18next";
import { Search } from "lucide-react";
import { modsApi, steamWorkshopApi } from "@/api";
import type { ModWishlistRequest, SteamWorkshopList, SteamWorkshopResult } from "@/types/models";
import { Input } from "@/components/ui/input";
import { SegmentedTabs, SegmentedTabsList, SegmentedTabsTrigger } from "@/components/ui/segmented-tabs";
import { SteamWorkshopCard } from "./SteamWorkshopCard";
import { useNotifications } from "@/hooks/useNotifications";

const LISTS: { value: SteamWorkshopList; key: string; fallback: string }[] = [{ value: "trending", key: "trending", fallback: "Trending" }, { value: "latest_added", key: "latestAdded", fallback: "Latest Added" }, { value: "latest_updated", key: "latestUpdated", fallback: "Latest Updated" }];
export function SteamWorkshopBrowser() {
 const { t }=useTranslation(); const notifications=useNotifications(); const [list,setList]=React.useState<SteamWorkshopList>("trending"); const [items,setItems]=React.useState<SteamWorkshopResult[]>([]); const [query,setQuery]=React.useState(""); const [loading,setLoading]=React.useState(false); const [wishlist,setWishlist]=React.useState<ModWishlistRequest[]>([]); const [busy,setBusy]=React.useState<string|null>(null); const [error,setError]=React.useState<string|null>(null);
 React.useEffect(()=>{modsApi.getWishlist().then(setWishlist)},[]);
 React.useEffect(()=>{const h=setTimeout(async()=>{setLoading(true);setError(null);try{const page=query.trim().length>=2?await steamWorkshopApi.searchMods(query.trim()):await steamWorkshopApi.getModList(list);setItems(page.results)}catch(e){setError(e instanceof Error?e.message:t("mods.steamBrowser.error", {defaultValue:"Failed to load Steam Workshop mods."}))}finally{setLoading(false)}},query?400:0);return()=>clearTimeout(h)},[list,query]);
 async function add(mod:SteamWorkshopResult){setBusy(mod.workshopId);try{const updated=await modsApi.addSteamToWishlist(mod);setWishlist(updated);notifications.success({title:t("mods.steamBrowser.requestedTitle", {defaultValue:"Added to server wishlist"}),message:t("mods.steamBrowser.requestedMessage", {defaultValue:"{{name}} is waiting for super-admin review.", name:mod.name})})}catch(e){notifications.error({title:t("mods.steamBrowser.addFailed", {defaultValue:"Could not add mod"}),message:e instanceof Error?e.message:t("common.unknownError", {defaultValue:"Unknown error."})})}finally{setBusy(null)}}
 return <div className="space-y-4"><div className="rounded-md border border-life-600/30 bg-life-500/5 px-3 py-2 text-xs text-life-400/90">{t("mods.steamBrowser.banner", {defaultValue:"Browse public Steam Workshop information and add mods to the server wishlist. The super admin decides whether to install each request."})}</div><SegmentedTabs value={list} onValueChange={v=>setList(v as SteamWorkshopList)}><SegmentedTabsList>{LISTS.map(x=><SegmentedTabsTrigger key={x.value} value={x.value}>{t(`mods.steamBrowser.${x.key}`, {defaultValue:x.fallback})}</SegmentedTabsTrigger>)}</SegmentedTabsList></SegmentedTabs><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-parchment-300/40"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("mods.steamBrowser.search", {defaultValue:"Search all Steam Workshop mods by name..."})} className="pl-9" autoFocus/></div>{error&&<p className="text-sm text-blood-400">{error}</p>}{loading?<p className="py-10 text-center text-parchment-300/50">{t("mods.steamBrowser.loading", {defaultValue:"Loading Steam Workshop..."})}</p>:<div className="grid max-h-[440px] grid-cols-1 gap-4 overflow-auto pr-1 md:grid-cols-2">{items.map(m=><SteamWorkshopCard key={m.workshopId} mod={m} busy={busy===m.workshopId} wishlisted={wishlist.some(w=>w.source==="steam"&&w.workshopId===m.workshopId)} onWishlist={()=>add(m)}/>)}</div>}</div>
}
