import * as React from "react";
import { useTranslation } from "react-i18next";
import { Download, HardDrive, RefreshCw, RotateCcw, ShieldCheck, Trash2 } from "lucide-react";
import { Panel } from "@/components/ui/panel";
import { ActionButton } from "@/components/ui/egm-button";
import { Modal } from "@/components/ui/modal";
import * as api from "@/api/backupCenterApi";
import type { BackupCenterResponse, BackupRecord } from "@/types/models";
import { useNotifications } from "@/hooks/useNotifications";

const size=(v:number)=>v>=1024**3?`${(v/1024**3).toFixed(2)} GB`:`${(v/1024**2).toFixed(1)} MB`;
export default function BackupCenter(){
 const {t}=useTranslation(); const notifications=useNotifications(); const [data,setData]=React.useState<BackupCenterResponse|null>(null); const [busy,setBusy]=React.useState(""); const [restore,setRestore]=React.useState<{id:string;b:BackupRecord}|null>(null);
 const load=React.useCallback(()=>api.listAllBackups().then(setData).catch(e=>notifications.error({title:t("backupCenter.loadFailed",{defaultValue:"Could not load backups"}),message:String(e)})),[notifications,t]); React.useEffect(()=>{load()},[load]);
 const run=async(id:string)=>{setBusy(`run:${id}`);try{await api.runInstanceBackup(id);notifications.success({title:t("backupCenter.complete",{defaultValue:"Backup complete"})});await load()}catch(e){notifications.error({title:t("backupCenter.failed",{defaultValue:"Backup failed"}),message:String(e)})}finally{setBusy("")}};
 const remove=async(id:string,ts:string)=>{if(!confirm(t("backupCenter.confirmDelete",{defaultValue:"Delete this backup permanently?"})))return;setBusy(`delete:${id}:${ts}`);try{await api.deleteInstanceBackup(id,ts);await load()}finally{setBusy("")}};
 const verify=async(id:string,ts:string)=>{setBusy(`verify:${id}:${ts}`);try{const r=await api.verifyInstanceBackup(id,ts);(r.status==="ok"?notifications.success:notifications.warning)({title:t("backupCenter.verifyResult",{defaultValue:"Verification: {{status}}",status:r.status}),message:r.issues.join("\n")})}finally{setBusy("")}};
 const doRestore=async()=>{if(!restore)return;setBusy("restore");try{await api.restoreInstanceBackup(restore.id,restore.b.timestamp);notifications.success({title:t("backupCenter.restored",{defaultValue:"Backup restored"})});setRestore(null);await load()}catch(e){notifications.error({title:t("backupCenter.restoreFailed",{defaultValue:"Restore failed"}),message:String(e)})}finally{setBusy("")}};
 return <div className="space-y-6"><Panel icon={<HardDrive/>} title={t("backupCenter.title",{defaultValue:"Backup Center"})}><div className="flex items-center justify-between gap-4"><div><p className="text-sm text-parchment-300/70">{t("backupCenter.description",{defaultValue:"Manage, verify, restore, export, and delete backups for every server instance."})}</p><p className="mt-1 text-xs text-mana-300/75">{t("backupCenter.scope")}</p></div><ActionButton variant="ghost" onClick={load}><RefreshCw className="h-4 w-4"/>{t("common.refresh",{defaultValue:"Refresh"})}</ActionButton></div></Panel>
 {!data?<p>{t("backupCenter.loading",{defaultValue:"Loading backups..."})}</p>:data.servers.map(group=><Panel key={group.instanceId} title={`${group.instanceName} · ${group.backups.length} · ${size(group.totalBytes)}`}><div className="mb-4 flex justify-end"><ActionButton onClick={()=>run(group.instanceId)} disabled={!!busy}><HardDrive className="h-4 w-4"/>{t("backupCenter.backupNow",{defaultValue:"Backup Now"})}</ActionButton></div>{group.backups.length===0?<p className="text-sm text-parchment-300/50">{t("backupCenter.none",{defaultValue:"No backups yet."})}</p>:<div className="space-y-2">{group.backups.map(b=><div key={b.timestamp} className="flex flex-col gap-3 rounded-md border border-stone-700/70 bg-abyss-950/30 p-3 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><p className="font-mono text-sm text-parchment-100">{b.timestamp}</p><p className="text-xs text-parchment-300/50">{b.kind} · {size(b.sizeBytes)} · {b.fileCount??"-"} files</p></div><div className="flex flex-wrap gap-2"><ActionButton size="sm" variant="ghost" onClick={()=>verify(group.instanceId,b.timestamp)}><ShieldCheck className="h-4 w-4"/>{t("backupCenter.verify",{defaultValue:"Verify"})}</ActionButton><ActionButton size="sm" variant="ghost" onClick={()=>window.open(api.backupCenterExportUrl(group.instanceId,b.timestamp),"_blank")}><Download className="h-4 w-4"/>{t("backupCenter.export",{defaultValue:"Export"})}</ActionButton><ActionButton size="sm" variant="ghost" onClick={()=>setRestore({id:group.instanceId,b})}><RotateCcw className="h-4 w-4"/>{t("backupCenter.restore",{defaultValue:"Restore"})}</ActionButton><ActionButton size="sm" variant="danger" onClick={()=>remove(group.instanceId,b.timestamp)}><Trash2 className="h-4 w-4"/>{t("common.delete",{defaultValue:"Delete"})}</ActionButton></div></div>)}</div>}</Panel>)}
 <Modal open={!!restore} onOpenChange={o=>!o&&setRestore(null)} title={t("backupCenter.restoreTitle",{defaultValue:"Restore backup?"})} description={t("backupCenter.restoreWarning",{defaultValue:"The selected server will be stopped if necessary and its current save will be replaced. A rollback snapshot is created automatically."})} confirmLabel={t("backupCenter.restore",{defaultValue:"Restore"})} onConfirm={doRestore} confirming={busy==="restore"}/>
 </div>
}
